name: otus_project_dbtvault
profile: otus_project
version: '0.1.0'
require-dbt-version: ['>=1.4.0', '<1.5.0']
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: target

vars:
  load_date: 'current_timestamp'

seeds:
  otus_project_dbtvault:
    source_client_type:
      +delimiter: ";"

models:
  otus_project_dbtvault:
    stage:
      tags:
        - 'stage'
      materialized: view
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
    business_vault:
      tags:
        - 'business_vault'
      materialized: view
    cdm:
      tags:
        - 'cdm'
      materialized: view
    marts:
      tags:
        - 'marts'
      materialized: view